stuvibe/main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
# app_name = 'stuvibe'
urlpatterns = [
    path('admin', admin.site.urls),
    path('', views.home,name='home'),
    path('signup',views.signup,name='signup'),
    path('edit_profile/<str:pk>',views.signup_edit,name='edit_profile'),
    path('createpost',views.create_post,name='create_post'),
    path('login',views.login_,name='login'),
    path('profile/<int:pk>',views.profile,name='profile'),
    path('liked/', views.like_unlike_post, name='like-post-view'),
    path('comments/<int:pk>', views.comments, name='comments'),
    path('create_portfolio', views.create_portfolio, name='create_portfolio'),
    path('createproject', views.createproject, name='createproject'),
    path('portfoliohome', views.PortfolioHome, name='PortfolioHome'),
    path('inbox/', views.inbox, name='inbox'),
    path('direct/<username>', views.Directs, name="directs"),
    path('send/', views.SendDirect, name="send-directs"),
    path('search/', views.UserSearch, name="search-users"),
    path('new/<username>', views.NewConversation, name="conversation"),
    path('direct/getMessages/<str:username>/', views.getMessages, name="getMessages"),
    path('portfolio', views.PortfolioHome, name="portfolio"),
    path('projects/<str:pk>', views.projects, name="projects"),
    path('search_users', views.search_users, name="search_users"),
    path('search_posts', views.search_posts, name="search_posts"),
    path('display_posts/<str:pk>', views.display_posts, name="display_posts"),
]
    

stuvibe/stuvibe/urls.py
from django.contrib import admin
from django.urls import path,include
import main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

stuvibe/main/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.db.models import Max
from . import choices 
from ckeditor_uploader.fields import RichTextUploadingField
class User(AbstractUser):
    username = models.CharField(max_length=100,unique=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100,null=True,blank=True)
    dob = models.DateField(null=True,blank=True)#
    profile_photo = models.ImageField(upload_to='./static/data/user_profile',blank=True,null=True)
    profile_banner = models.ImageField(upload_to='./static/data/profile_banner',blank=True,null=True)
    degree = models.TextField(null=True,blank=True)
    branch = models.TextField(null=True,blank=True)
    country = models.TextField(null=True,blank=True)
    state = models.TextField(max_length=100,null=True,blank=True)
    district = models.TextField(max_length=100,null=True,blank=True)
    bio = models.TextField(null=True,blank=True)
    university = models.TextField(null=True,blank=True)
    aspiring = models.TextField(null=True,blank=True)
    gender = models.TextField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    followers = models.ManyToManyField('self',blank=True)
    following = models.ManyToManyField('self',blank=True)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []
    def __str__(self):
        return self.username
    
class PostDetails(models.Model):
    host = models.ForeignKey(User,on_delete=models.CASCADE,related_name='host')
    title = models.CharField(max_length=100)
    template = models.ImageField(upload_to='./static/data/post_templates',null=True,blank=True)
    content = models.TextField(blank=True,null=True)
    tags = models.TextField(blank=True,null=True)
    likes = models.ManyToManyField(User,related_name='liked_post',blank=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-updated','-created']
    def __str__(self):
        return self.title
    
class Post(models.Model):
    post_details = models.ForeignKey(PostDetails,on_delete=models.CASCADE,related_name='post_details')
    post = models.FileField(upload_to='./static/data/posts')
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-updated','-created']
    

class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(PostDetails,on_delete=models.CASCADE,related_name='comments')
    content = models.TextField()
    likes = models.ManyToManyField(User,related_name='liked_comment',blank=True)
    parent_comment = models.ForeignKey('self',on_delete=models.CASCADE,related_name='replies',null=True,blank=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-updated','-created']
    def __str__(self):
        return self.content

    

class Stories(models.Model):
    host = models.ForeignKey(User,on_delete=models.CASCADE)
    story = models.FileField(upload_to='./static/data/stories')
    tags = models.TextField(blank=True,null=True)
    likes = models.ManyToManyField(User,related_name='liked_Story',blank=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
 
    

    
LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(PostDetails, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    

job_type_choices = [
    ('freelancer','freelancer'),
    ('job','job')
]
flexibility_choices = [
    ('fulltime','fulltime'),
    ('parttime','parttime')
]
class Portfolio(models.Model):
    portfolio_user = models.ForeignKey(User,on_delete=models.CASCADE)
    portfolio_username = models.CharField(max_length=500,default='')
    followers = models.ManyToManyField(User,related_name='portfolio_followers',blank=True)
    job_type = models.TextField(choices=job_type_choices)
    flexibility = models.TextField(choices=flexibility_choices)
    domain = models.TextField(blank=True,null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.portfolio_username

class PortfolioProjectsDetails(models.Model):
    portfolio = models.ForeignKey(Portfolio,related_name='portfolio',on_delete=models.CASCADE)
    title = models.CharField(max_length=60)
    description = models.TextField(blank=True,null=True)
    tags = models.TextField(blank=True,null=True)
    tools_used = models.TextField(blank=True,null=True)
    project_cover = models.ImageField(upload_to='./static/data/project_cover',null=True,blank=True)
    appreciations = models.ManyToManyField(User,related_name='appreciations',blank=True)
    views = models.ManyToManyField(User,related_name='portfolio_views',blank=True)
    project_files = RichTextUploadingField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.title



class Message(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user')
    reciepient = models.ForeignKey(User,on_delete=models.CASCADE,related_name='to_user')
    sender = models.ForeignKey(User,on_delete=models.CASCADE,related_name='from_user')
    is_read = models.BooleanField(default=False)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def sender_message(from_user,to_user,body):
        sender_message = Message(
            user = from_user,
            sender = from_user,
            reciepient = to_user,
            body = body,
            is_read = True
        )
        sender_message.save()
        reciepient_message = Message(
            user = to_user,
            sender = from_user,
            reciepient = from_user,
            body = body,
            is_read = True
        )
        reciepient_message.save()

        return sender_message
    def get_message(user):
        users = []
        messages = Message.objects.filter(user = user).values('reciepient').annotate(last=Max('date')).order_by("-last")
        for message in messages:
            users.append({
                'user':User.objects.get(pk=message['reciepient']),
                'last':message['last'],
                'unread':Message.objects.filter(user=user,reciepient__pk = message['reciepient'],is_read = False).count()
            })
        return users

 
 

stuvibe/main/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . import models
from ckeditor.widgets import CKEditorWidget

class UserForm(UserCreationForm):
    class Meta:
        model = models.User
        fields = ['username','email','first_name','last_name','dob','profile_photo','profile_banner','degree','branch','country','state','district','bio','university','gender']

class CreatePost(ModelForm):
    class Meta:
        model = models.PostDetails
        fields = ['title','content','tags']
class CreateComment(ModelForm):
    class Meta:
        model = models.Comment
        fields = ['content']
class PortfolioForm(ModelForm):
    class Meta:
        model = models.Portfolio
        fields = ['portfolio_username','job_type','flexibility','domain']
        
class PortfolioProjectsDetailsForm(ModelForm):
    class Meta:
        model = models.PortfolioProjectsDetails
        fields = ['project_files','project_cover']


 

stuvibe/main/templates/create_portfolio.html
<link rel="stylesheet" href="../static/styles/create_portfolio.css?{ now 'U' %}">
{% extends 'main.html' %}
{% block content %}
<main>
    <form action="" method="post">
        <p id="title">create portfolio</p>
        {% csrf_token %}
        <div class="form_con">
            <div class="input_area ">
                <label for="">username:</label>
                <input type="text" name="portfolio_username" class="portfolio_username" required placeholder="Type you username...">
            </div>
            <div class="input_area">
                <label for="id_domain">Job type:</label>
                <select name="job_type" required="" id="id_job_type">
                    <option value="" selected="">---------</option>
                  
                    <option value="freelancer">freelancer</option>
                  
                    <option value="job">job</option>
                  
                  </select>
            </div>
            <div class="input_area ">
                <label for="id_domain">flexibility:</label>
                <select name="flexibility" required="" id="id_flexibility">
                    <option value="" selected="">---------</option>
                  
                    <option value="fulltime">fulltime</option>
                  
                    <option value="parttime">parttime</option>
                  
                  </select>
            </div>
            <div class="input_area ">
                <label for="id_domain">Domain:</label>
                <input type="text" name="domain" class="domain" required placeholder="Type you domain...">
            </div>
        </div>
        <button type="submit" class="sub_btn">submit</button>
    </form>
</main>
{% endblock content %}

stuvibe/main/templates/createproject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>portfolio</title>
    <link rel="stylesheet" href="./static/styles/createproject.css?{% now 'U' %}">
    <!-- <link rel="stylesheet" href="../static/styles/styles.css?{ now 'U' %}"> -->
    <link rel="stylesheet" href="../static/styles/leftbar.css?{ now 'U' %}">
</head>
<body>
    <div class="background_cover">
        <img src="../static/assests/aesthetic-retro-vaporwave-landscape.jpg" alt="">
    </div>
    <div class="leftsidebar">
        {% include 'leftbar.html' %}
    </div>
    <form action="" method="post" enctype="multipart/form-data" class="con_form">
        <div class="section_1">
            <div class="main_con">
                <p >Create Project</p>
                <div class="details_con">
                    <div class="input_area ">
                        <label for="">Title:</label>
                        <input type="text" name="title" class="title" required placeholder="Type your title...">
                    </div>
                    <div class="input_area ">
                        <label for="">description:</label>
                        <input type="text" name="description" class="description" placeholder="Type your description...">
                    </div>
                    <div class="input_area ">
                        <label for="">tags:</label>
                        <input type="text" name="tags" class="tags" placeholder="Type your tags...">
                    </div>               
                    <div class="input_area ">
                        <label for="">tools Used:</label>
                        <input type="text" name="tools_used" class="tools_used" placeholder="Type your tools_used...">
                    </div>
                    <div class="input_area ">
                        <label for="">project cover:</label>
                        <input type="file" name="project_cover" class="project_cover">
                    </div>
                </div>
                <button type="button" class="next btn" onclick="change()">next</button>
            </div>
        </div>
        <div class="section_2 activate">
            {% csrf_token %}
            <div class="form_main_container">
                {{form.as_p}}
                {{form.media}}
            </div>
            <button type="submit" class="sub_btn">submit</button>
            <button type="button" class="previous btn" onclick="change()">
                    <?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
                    <svg width="800px" height="800px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <polyline fill="none" stroke="#000000" stroke-width="2" points="7 2 17 12 7 22" transform="matrix(-1 0 0 1 24 0)"/>
                    </svg>
            </button>    
        </div>
    </form>
    <script>
        let btn = document.querySelector('.btn')
        change=()=>{
            document.querySelector('.section_1').classList.toggle('activate')
            document.querySelector('.section_2').classList.toggle('activate')
        }
    </script>
</body>
</html>

stuvibe/main/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="static/styles/login.css?{% now 'U' %}">
</head>
<body>
    <main>
        <div class="cover_image"></div>
        <div class="title">
            <p>stuvibe</p>
        </div>
        <div class="container">
            <div class="login_header">
                <div class="login_header_title">
                    <p>Login</p>
                </div>
                <div class="login_header_signup">
                    <p>Dosen't Has An Account? </p>
                    <a href="{% url 'signup' %}">Signup</a>
                </div>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="login_container">
                    <div class="login_input_container">
                        <div class="input_container">
                            <label>Username</label>
                            <input required type="text" name="username">
                        </div>
                        <div class="input_container">
                            <label>password</label>
                            <input required type="password" name="password">
                        </div>
                    </div>
                </div>
                <button type="submit" class="sub_btn">Login</button>
            </form>
        </div>
    </main>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // Get all form elements
            const forms = document.querySelectorAll("form");
        
            // Attach event listener to each form
            forms.forEach(function(form) {
                form.addEventListener("keydown", function(event) {
                    // Check if the pressed key is Enter and the target is not a textarea
                    if (event.key === "Enter" && event.target.tagName !== "TEXTAREA") {
                        // Prevent the default form submission behavior
                        event.preventDefault();
                    }
                });
            });
        });
        </script>
</body>
</html>

stuvibe/main/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>stuvibe</title>
    <link rel="stylesheet" href="../static/styles/leftbar.css?{% now 'U' %}">
</head>
<body>
    {% include 'leftbar.html' %}
    {% block content %}
    {% endblock  %}
</body>
</html>

stuvibe/main/templates/portfolio.html
{% extends 'main.html' %}

{% block content %} 
<link rel="stylesheet" href="../static/styles/portfolio.css?{% now 'U' %}">
<header>
    <div class="header_left">
        <p class="title">portfolios</p>
        <div class="links">
            <a href="#">For you</a>
            <a href="#">Discover</a>
            <a href="#">Hire</a>
        </div> 
    </div>
    <div class="search">
        <div class="search_logo">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path d="M6.12117 10.7424C8.94951 10.7424 11.2423 8.44958 11.2423 5.62121C11.2423 2.79285 8.94951 0.5 6.12117 0.5C3.29282 0.5 1 2.79285 1 5.62121C1 8.44958 3.29282 10.7424 6.12117 10.7424Z" stroke="white" stroke-linejoin="round"/>
                <mask id="path-2-inside-1_606_13" fill="white">
                  <path d="M13.328 13.3846C13.4819 13.5384 13.7313 13.5384 13.8852 13.3846C14.039 13.2308 14.039 12.9813 13.8852 12.8275L13.328 13.3846ZM13.8852 12.8275L9.94585 8.88806L9.38867 9.44525L13.328 13.3846L13.8852 12.8275Z"/>
                </mask>
                <path d="M13.5317 12.4739L12.9745 13.0311L13.6816 13.7382L14.2388 13.181L13.5317 12.4739ZM13.328 13.3846L12.6209 14.0917L12.6211 14.0919L13.328 13.3846ZM13.8852 13.3846L14.5921 14.0919L14.5925 14.0916L13.8852 13.3846ZM13.8852 12.8275L14.5925 12.1205L14.5923 12.1204L13.8852 12.8275ZM9.94585 8.88806L10.653 8.18096L9.94585 7.47384L9.23874 8.18096L9.94585 8.88806ZM9.38867 9.44525L8.68156 8.73815L7.97446 9.44525L8.68156 10.1524L9.38867 9.44525ZM12.6211 14.0919C13.1655 14.636 14.0478 14.636 14.5921 14.0919L13.1783 12.6774C13.4149 12.4409 13.7983 12.4409 14.035 12.6774L12.6211 14.0919ZM14.5925 14.0916C15.1366 13.5472 15.1366 12.6649 14.5925 12.1205L13.1779 13.5344C12.9414 13.2978 12.9414 12.9143 13.1779 12.6777L14.5925 14.0916ZM14.5923 12.1204L10.653 8.18096L9.23874 9.59517L13.1781 13.5346L14.5923 12.1204ZM9.23874 8.18096L8.68156 8.73815L10.0958 10.1524L10.653 9.59517L9.23874 8.18096ZM8.68156 10.1524L12.6209 14.0917L14.0351 12.6775L10.0958 8.73815L8.68156 10.1524Z" fill="white" mask="url(#path-2-inside-1_606_13)"/>
              </svg>
        </div>
        <input type="text" placeholder="Search Here..">
    </div>
    <a href="{% url 'createproject' %}" class="share">
        <button>Share Your Work</button>
    </a>
</header>
<main>
    {% if portfolio_display%}
        <div class="main">
            {% for portfolio in portfolios %}
                <a href="{% url 'projects' portfolio.id %}">
                    <div class="portfolio_con">
                        <div class="project_cover">
                            <img src="{{portfolio.project_cover.url}}" alt="">
                        </div>
                        <div class="project_details_con">
                            <div class="project_host">
                                <div class="project_host_profile">
                                    <img src="{{portfolio.portfolio.portfolio_user.profile_photo.url}}" alt="" srcset="">
                                </div>
                                <p>{{portfolio.portfolio.portfolio_user}}</p>
                            </div>
                            <div class="project_details">
                                <div class="prj_likes">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="14" viewBox="0 0 12 14" fill="none">
                                        <path d="M10.0922 12.9143C10.5616 12.8054 11.0371 12.4968 11.0371 11.916C11.0371 11.6801 10.9709 11.5168 10.8926 11.3776C10.8445 11.299 10.8505 11.2385 10.9227 11.2082C11.3018 11.0388 11.6148 10.7 11.6148 10.21C11.6148 9.93776 11.5426 9.68973 11.4042 9.51425C11.3379 9.42352 11.35 9.35094 11.4583 9.28439C11.7412 9.12706 11.9217 8.77619 11.9217 8.3769C11.9217 8.09861 11.8314 7.79007 11.6629 7.63881C11.5727 7.55412 11.5907 7.49361 11.693 7.40892C11.8917 7.25768 12 6.96729 12 6.62243C12 6.02954 11.5426 5.55162 10.9408 5.55162H8.79234C8.25071 5.55162 7.88361 5.26727 7.88361 4.8196C7.88361 3.98471 8.91269 2.48435 8.91269 1.40143C8.91269 0.838792 8.54561 0.5 8.07018 0.5C7.63688 0.5 7.41421 0.802473 7.1795 1.26227C6.28281 3.04092 5.06718 4.47474 4.14641 5.70286C3.36409 6.75555 2.97893 7.63881 2.96088 9.0908C2.93076 11.3232 4.73017 13.0232 7.55864 13.0474L8.39514 13.0534C9.1835 13.0595 9.76123 12.999 10.0922 12.9143ZM0 9.13313C0 10.9481 1.11936 12.4666 2.62988 12.4666H3.7071C2.61784 11.668 2.11835 10.458 2.1424 9.07262C2.16046 7.53597 2.75626 6.44094 3.28585 5.77547H2.4012C1.04713 5.77547 0 7.25162 0 9.13313Z" fill="#808080"/>
                                    </svg>
                                    <p>{{portfolio.appreciations.count}}</p>
                                </div>
                                <div class="prj_views">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="12" viewBox="0 0 15 12" fill="none">
                                        <path d="M14.9334 5.72693C14.8474 5.51289 12.7616 0.5 7.5 0.5C2.23839 0.5 0.15264 5.51289 0.0666227 5.72693C-0.0222076 5.94816 -0.0222076 6.19493 0.0666227 6.41616C0.15264 6.62996 2.23839 11.6429 7.5 11.6429C12.7616 11.6429 14.8474 6.62997 14.9334 6.41593C15.0222 6.1947 15.0222 5.94816 14.9334 5.72693ZM7.5 7.92857C6.46451 7.92857 5.62496 7.09704 5.62496 6.07143C5.62496 5.04582 6.46451 4.21429 7.5 4.21429C8.53549 4.21429 9.37504 5.04582 9.37504 6.07143C9.37504 7.09704 8.53549 7.92857 7.5 7.92857Z" fill="#808080"/>
                                    </svg>
                                    <p>{{portfolio.views.count}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    {% else %}
    
        <div class="container">
            <div class="project_host_">
                <div class="project_host_profile_photo">
                    <img src="{{project.portfolio.portfolio_user.profile_photo.url}}" alt="{{project.portfolio.portfolio_user.profile_photo}}">
                </div>
                <p>{{project.portfolio.portfolio_user}}</p>
            </div>
            <div class="display_container">
                {{project_files|safe}}
            </div>
            <div class="project_features">
                <div class="follow">
                    <div class="follow_svg">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="19" viewBox="0 0 20 19" fill="none">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M2.99219 7.50232C2.99219 5.01627 5.00754 3.00092 7.49359 3.00092C9.97967 3.00092 11.995 5.01627 11.995 7.50232C11.995 9.9884 9.97967 12.0037 7.49359 12.0037C5.00754 12.0037 2.99219 9.9884 2.99219 7.50232Z" fill="#1E90FF"/>
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M2.63563 13.7035C3.86837 13.1685 5.48582 13.004 7.49595 13.004C9.50782 13.004 11.1264 13.1688 12.3596 13.705C13.7029 14.2891 14.5194 15.284 14.9473 16.6888C15.1479 17.3472 14.6533 18.0056 13.9718 18.0056H1.02198C0.339649 18.0056 -0.155946 17.3462 0.0452371 16.6866C0.473741 15.2816 1.29144 14.287 2.63563 13.7035Z" fill="#1E90FF"/>
                            <path d="M16.9977 1.00031C16.9977 0.44786 16.5498 0 15.9973 0C15.4449 0 14.997 0.44786 14.997 1.00031V3.00094H12.9964C12.4439 3.00094 11.9961 3.4488 11.9961 4.00125C11.9961 4.5537 12.4439 5.00156 12.9964 5.00156H14.997V7.00219C14.997 7.55464 15.4449 8.0025 15.9973 8.0025C16.5498 8.0025 16.9977 7.55464 16.9977 7.00219V5.00156H18.9983C19.5508 5.00156 19.9986 4.5537 19.9986 4.00125C19.9986 3.4488 19.5508 3.00094 18.9983 3.00094H16.9977V1.00031Z" fill="#1E90FF"/>
                        </svg>
                    </div>
                    <p>Follow</p>
                </div>
                <div class="appreciate">
                    <div class="appreciate_svg">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="22" viewBox="0 0 20 22" fill="none">
                            <path d="M16.8204 20.8186C17.6027 20.636 18.3951 20.1185 18.3951 19.1446C18.3951 18.7489 18.2848 18.475 18.1544 18.2416C18.0741 18.1097 18.0842 18.0083 18.2045 17.9576C18.8363 17.6735 19.3581 17.1053 19.3581 16.2836C19.3581 15.827 19.2377 15.4111 19.007 15.1168C18.8965 14.9646 18.9167 14.8429 19.0972 14.7313C19.5686 14.4675 19.8696 13.8791 19.8696 13.2094C19.8696 12.7428 19.719 12.2253 19.4382 11.9717C19.2878 11.8297 19.3178 11.7282 19.4883 11.5862C19.8195 11.3325 20 10.8456 20 10.2672C20 9.27297 19.2377 8.4715 18.2346 8.4715H14.6539C13.7512 8.4715 13.1393 7.99464 13.1393 7.24391C13.1393 5.84382 14.8545 3.32773 14.8545 1.51169C14.8545 0.568149 14.2427 0 13.4503 0C12.7281 0 12.357 0.507243 11.9658 1.27832C10.4713 4.26109 8.44531 6.66559 6.91068 8.72512C5.60681 10.4905 4.96489 11.9717 4.9348 14.4067C4.8846 18.1503 7.88362 21.0012 12.5977 21.0418L13.9919 21.0519C15.3058 21.0621 16.2687 20.9606 16.8204 20.8186ZM0 14.4776C0 17.5213 1.8656 20.0678 4.38313 20.0678H6.17851C4.36306 18.7286 3.53058 16.6995 3.57067 14.3762C3.60076 11.7992 4.59377 9.96288 5.47641 8.84689H4.002C1.74522 8.84689 0 11.3224 0 14.4776Z" fill="white"/>
                          </svg>
                    </div>
                    <p>Appreciate</p>
                </div>
            </div>
        </div>
    {% endif %}
</main>
{% endblock content %}

stuvibe/main/templates/user_profile_edit.html
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">edit</button>
</form>